### ISSUE TITLE
settings.ini options

### ISSUE THREAD

**Issue by cgomesu** [jsaddiction/TrailerTech#18]
The [Settings wiki](https://github.com/jsaddiction/TrailerTech/wiki/Settings) only describes the `api_key` option but the default file contains many other options.  All such options seem to be parsed with Ptyhon's `configparser` in the `utils/config.py` file but some of the `Config()` properties are not referred to anywhere else in the TrailerTech program.  The `.apple_enabled` property, for example, is not used to enable/disable Apple as a provider, and therefore, the configuration

```
[APPLE]
enabled=false
```

is not being obeyed.  I think the same is true for Youtube.  Maybe I missed something.  Could you confirm this?

**Comment by jsaddiction** [comment]
Thanks for the detailed description! I've pushed the fix to the main branch
