### ISSUE TITLE
Radarr custom script exited with code: 1

### ISSUE THREAD

**Issue by Tippon** [jsaddiction/TrailerTech#45]
I've followed the guides and got TrailerTech running properly, and I've downloaded most of the trailers for my library. When I try to add TrailerTech to Radarr though, I get the "Script exited with code: 1" error message. 

I've checked the Radarr log and I'm getting an error when importing tmdbsimple - "ModuleNotFoundError: No module named 'tmdbsimple'", then getting a validation failed error - "FluentValidation.ValidationException: Validation failed: 
 -- : Script exited with code: 1". I'll attach the full log to the bottom.

I've tried installing tmdbsimple, but get the following error:

"python3 -m pip install tmdbsimple
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: tmdbsimple in /home/media/.local/lib/python3.10/site-packages (2.9.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from tmdbsimple) (2.25.1)"

Checking the python and pip versions gives me these:

python3 --version
Python 3.10.4
pip --version
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

I've tried all the fixes I can find by Googling, but get the same result. The only thing I haven't tried is a virtual environment, as I don't want to confuse things further.

If you could point me in the right direction, I would be very grateful :)

Radarr debug log:

"2022-06-21 17:44:01.2|Debug|Api|[GET] /api/v3/command: 200.OK (0 ms)
2022-06-21 17:44:01.2|Debug|Api|[GET] /api/v3/command: 200.OK (0 ms)
2022-06-21 17:44:01.3|Debug|Api|[GET] /api/v3/log/file: 200.OK (0 ms)
2022-06-21 17:44:06.0|Debug|CustomScript|Executing external script: /home/(removed)/Arr/TrailerTech/TrailerTech.py
2022-06-21 17:44:06.0|Debug|TrailerTech.py|Starting /home/(removed)/Arr/TrailerTech/TrailerTech.py 
2022-06-21 17:44:06.0|Error|TrailerTech.py|Traceback (most recent call last):
2022-06-21 17:44:06.0|Error|TrailerTech.py|  File "/home/(removed)/Arr/TrailerTech/TrailerTech.py", line 10, in <module>
2022-06-21 17:44:06.0|Error|TrailerTech.py|    from providers.tmdb import Tmdb
2022-06-21 17:44:06.0|Error|TrailerTech.py|  File "/home/(removed)/Arr/TrailerTech/providers/tmdb.py", line 3, in <module>
2022-06-21 17:44:06.1|Error|TrailerTech.py|    import tmdbsimple as tmdb
2022-06-21 17:44:06.1|Error|TrailerTech.py|ModuleNotFoundError: No module named 'tmdbsimple'
2022-06-21 17:44:06.1|Debug|CustomScript|Executed external script: /home/(removed)/Arr/TrailerTech/TrailerTech.py - Status: 1
2022-06-21 17:44:06.1|Debug|CustomScript|Script Output: 
21/06/2022 16:44:06 - Error - Traceback (most recent call last):
21/06/2022 16:44:06 - Error -   File "/home/(removed)/Arr/TrailerTech/TrailerTech.py", line 10, in <module>
21/06/2022 16:44:06 - Error -     from providers.tmdb import Tmdb
21/06/2022 16:44:06 - Error -   File "/home/(removed)/Arr/TrailerTech/providers/tmdb.py", line 3, in <module>
21/06/2022 16:44:06 - Error -     import tmdbsimple as tmdb
21/06/2022 16:44:06 - Error - ModuleNotFoundError: No module named 'tmdbsimple'
2022-06-21 17:44:06.1|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.1.0.6175] FluentValidation.ValidationException: Validation failed: 
 -- : Script exited with code: 1
   at Radarr.Api.V3.ProviderControllerBase`3.VerifyValidationResult(ValidationResult validationResult, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 205
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderDefinition definition, Boolean includeWarnings) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 191
   at Radarr.Api.V3.ProviderControllerBase`3.Test(TProviderResource providerResource) in D:\a\1\s\src\Radarr.Api.V3\ProviderControllerBase.cs:line 140
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

2022-06-21 17:44:06.1|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Script exited with code: 1
2022-06-21 17:44:06.1|Debug|Api|[POST] /api/v3/notification/test: 400.BadRequest (120 ms)"

**Comment by Tippon** [comment]
I've been looking into this more to see if I can figure out what's stopping the script from working with Radarr, and I found a test script on the tmdbsimple Github page:

[https://github.com/celiao/tmdbsimple/issues/83#issuecomment-1019328326](url)

`import tmdbsimple as tmdb
tmdb.API_KEY = 'xxxxxxxxxxxxxxxxxxxxxxxxx'
BREAKING_BAD = 1396;
first_air_date = tmdb.TV(BREAKING_BAD).info()['first_air_date'];
print("First Air Date =", first_air_date)`

When I run this from the terminal, it works perfectly, just like running TrailerTech from the terminal. The problem seems to be something to do with Radarr calling the script, rather than a problem with tmdbsimple as I originally thought.

**Comment by jsaddiction** [comment]
Can you please provide some more details on your environment?  It seems to me that maybe when you are calling the script directly, you are using one version of python and a different one when called directly from radarr

**Comment by Tippon** [comment]
Thanks for replying :)

As far as I can tell, there's just the one Python version installed. 

python3 --version
Python 3.10.4
pip --version
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

I'm running Xubuntu 22.04 LTS and reinstalled Python a few hours ago as part of the troubleshooting. It didn't make a difference to the error though.

**Comment by jsaddiction** [comment]
is Radarr being run in a docker container?  if so run `docker exec -it radarr /bin/bash` to get you into the container then run `python3` this will open the REPL cli.  Once you are in there run `import tmdbsimple as tmdb` if no error then everything is fine with that import statement.  `exit()` to exit REPL `exit` to exit the docker container

**Comment by Tippon** [comment]
Sorry, I should have mentioned, I don't use Docker. I'm running everything natively to try and squeeze the last few drops of performance out of the server.

**Comment by Tippon** [comment]
I tried running the commands in a terminal window, and import seemed to work ok:

'~$ python3

Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux

Type "help", "copyright", "credits" or "license" for more information.

>>> import tmdbsimple as tmdb

>>>'

**Comment by jsaddiction** [comment]
The only thing I can think that would cause this issue is that you have more than one version of python installed.  ie., (python3.8 / python3.9) or similar.  Maybe you have similinks for python > python3.9 or something to that effect.  When radarr calls this script which has a shebang of `/usr/bin/env python3` which might refer to a different python installation.  

Run `find /etc -name python*` or something to that effect to find out which ones you have installed.  Since your executing the script at all, you know that at least some version of python is being used, but again the requirements haven't been installed for the version Radarr is using.

**Comment by Tippon** [comment]
You're right. I thought I'd uninstalled the previous versions, but there are at least some files left behind

`media@Media:~$ find /etc -name python*
find: ‘/etc/ssl/private’: Permission denied
/etc/python3.10
/etc/apparmor.d/abstractions/python
find: ‘/etc/polkit-1/localauthority’: Permission denied
/etc/python2.7
find: ‘/etc/wireguard’: Permission denied
/etc/python3.9
/etc/python3
find: ‘/etc/cups/ssl’: Permission denied
media@Media:~$ sudo find /etc -name python*
[sudo] password for media: 
/etc/python3.10
/etc/apparmor.d/abstractions/python
/etc/python2.7
/etc/python3.9
/etc/python3
media@Media:~$ 

`

**Comment by jsaddiction** [comment]
run `python3.9 -m pip install tmdbsimple` and compare to python3.10

I bet you have a similink which references to one python3 and radarr is calling the script with the other.  

To reduce confusion, i would dig through the similink stuff and change them to relate to 3.10 and remove all references to 3.9.  This way you only have one "python3" then run the commands to install the requirements for this script.  You should then be in business.

**Comment by Tippon** [comment]
I get python3.9: command not found

In /home/media/.local/lib/ I've got both python3.9 and python3.10, but that's after restoring the python3.9 folder.

Time to go digging >.<

**Comment by Tippon** [comment]
The symlinks in /usr/bin/ seem to point to python3.10, so I tried installing the dependencies with python3 -m pip install -r requirements.txt and got this:

`media@Media:~/Arr/TrailerTech$ python3 -m pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests>=2.20.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.25.1)
Requirement already satisfied: yt-dlp>=2022.04.08 in /home/media/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2022.5.18)
Requirement already satisfied: tmdbsimple>=2.7.0 in /home/media/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (2.9.1)
Requirement already satisfied: unidecode>=1.1.1 in /home/media/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (1.3.4)
Requirement already satisfied: mutagen in /home/media/.local/lib/python3.10/site-packages (from yt-dlp>=2022.04.08->-r requirements.txt (line 2)) (1.45.1)
Requirement already satisfied: websockets in /home/media/.local/lib/python3.10/site-packages (from yt-dlp>=2022.04.08->-r requirements.txt (line 2)) (10.3)
Requirement already satisfied: pycryptodomex in /usr/lib/python3/dist-packages (from yt-dlp>=2022.04.08->-r requirements.txt (line 2)) (3.11.0)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from yt-dlp>=2022.04.08->-r requirements.txt (line 2)) (2020.6.20)
Requirement already satisfied: brotli in /home/media/.local/lib/python3.10/site-packages (from yt-dlp>=2022.04.08->-r requirements.txt (line 2)) (1.0.9)
media@Media:~/Arr/TrailerTech$ 
`

Some packages are installed in /home/media/.local/lib/python3.10/site-packages but others are being installed in /usr/lib/python3/dist-packages. I tried copying tmdbsimple to /usr/lib/python3/dist-packages to test if that was part of the problem, and the error message changed. I'm still getting a code 1 error, but now it's looking for yt_dlp, which is in /home/media/.local/lib/python3.10/site-packages. I'll copy the full error message to the bottom of the post.

Would this be caused by the symlink problem, or is this something else? It looks like I can just copy the needed packages over, but that would just be a temporary fix, so I'd rather get it resolved.

Thanks again for helping me :)

New Code 1 error:
`2022-07-31 02:16:03.4|Debug|Api|[GET] /api/v3/filesystem?path=%2Fhome%2Fmedia%2FArr%2FTrailerTech%2FTrailerTech.py&allowFoldersWithoutTrailingSlashes=true&includeFiles=true: 200.OK (0 ms)
2022-07-31 02:16:07.7|Debug|CustomScript|Executing external script: /home/(removed)/Arr/TrailerTech/TrailerTech.py
2022-07-31 02:16:07.7|Debug|TrailerTech.py|Starting /home/(removed)/Arr/TrailerTech/TrailerTech.py 
2022-07-31 02:16:08.0|Error|TrailerTech.py|Traceback (most recent call last):
2022-07-31 02:16:08.0|Error|TrailerTech.py|  File "/home/(removed)/Arr/TrailerTech/TrailerTech.py", line 12, in <module>
2022-07-31 02:16:08.0|Error|TrailerTech.py|    from downloaders.downloader import Downloader
2022-07-31 02:16:08.0|Error|TrailerTech.py|  File "/home/(removed)/Arr/TrailerTech/downloaders/downloader.py", line 5, in <module>
2022-07-31 02:16:08.0|Error|TrailerTech.py|    import yt_dlp
2022-07-31 02:16:08.0|Error|TrailerTech.py|ModuleNotFoundError: No module named 'yt_dlp'
2022-07-31 02:16:08.0|Debug|CustomScript|Executed external script: /home/(removed)/Arr/TrailerTech/TrailerTech.py - Status: 1
2022-07-31 02:16:08.0|Debug|CustomScript|Script Output: 
31/07/2022 01:16:08 - Error - Traceback (most recent call last):
31/07/2022 01:16:08 - Error -   File "/home/(removed)/Arr/TrailerTech/TrailerTech.py", line 12, in <module>
31/07/2022 01:16:08 - Error -     from downloaders.downloader import Downloader
31/07/2022 01:16:08 - Error -   File "/home/(removed)/Arr/TrailerTech/downloaders/downloader.py", line 5, in <module>
31/07/2022 01:16:08 - Error -     import yt_dlp
31/07/2022 01:16:08 - Error - ModuleNotFoundError: No module named 'yt_dlp'
2022-07-31 02:16:08.0|Error|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.

[v4.1.0.6175] FluentValidation.ValidationException: Validation failed: 
 -- : Script exited with code: 1`

**Comment by jsaddiction** [comment]
Python doesn't really work that way. There is a hierarchal way that imports are conducted.  Moving directories around between versions isn't a good idea.  I would suggest removing both python3 versions and their associated similinks.  The reinstall python. Then start at the top with your install of this script to ensure everything went well.

**Comment by Tippon** [comment]
Apologies for not coming back to this sooner. I still haven't had any luck. Python can't be removed from Ubuntu as the OS relies on it.

sudo find /etc -name python* now gives
/etc/python3.10
/etc/apparmor.d/abstractions/python
/etc/python3

I had an issue with another script - Codex, from here:

[](https://github.com/ajslater/codex)

but downgrading setuptools resolved that. (Answer taken from here - [](https://askubuntu.com/questions/1406952/what-is-the-meaning-of-this-pkgresourcesdeprecationwarning-warning-from-pipenv)

I don't know if that's helpful at all, but I have no idea what to do

**Comment by jsaddiction** [comment]
From what you have listed as the result from your find command I would suspect that "python3" is a symlink for python 3.10.

To confirm this run `ls -all /etc | grep python`

A link will be listed as such and what it refers to will also be listed. Confirm that this is the case and try to install the dependencies again with the requirements file.

As a side note, be sure you are using the latest commit as some things have changed (don't think any of it applies to your installation though)

**Comment by Tippon** [comment]
> From what you have listed as the result from your find command I would suspect that "python3" is a symlink for python 3.10.
> 
> To confirm this run `ls -all /etc | grep python`

This is what I got from running that:

> ls -all /etc | grep python
> drwxr-xr-x   2 root      root    4096 Apr 20  2021 python3
> drwxr-xr-x   2 root      root    4096 Sep 24 00:18 python3.10


> A link will be listed as such and what it refers to will also be listed. Confirm that this is the case and try to install the dependencies again with the requirements file.
> 
> As a side note, be sure you are using the latest commit as some things have changed (don't think any of it applies to your installation though)

I did a Git Pull and installed the dependencies and tried reinstalling python and ffmpeg just in case and got the messages that everything is up to date:

>media@Media:~/Arr/TrailerTech$ git pull
>Already up-to-date.
>media@Media:~/Arr/TrailerTech$ sudo apt install git python3 python3-pip ffmpeg -y
>[sudo] password for media: 
>Reading package lists... Done
>Building dependency tree... Done
>Reading state information... Done
>python3-pip is already the newest version (22.0.2+dfsg-1).
>git is already the newest version (1:2.34.1-1ubuntu1.4).
>python3 is already the newest version (3.10.6-1~22.04).
>ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
>0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
>media@Media:~/Arr/TrailerTech$ python3 -m pip install -r requirements.txt
>Defaulting to user installation because normal site-packages is not writeable
>Requirement already satisfied: requests>=2.20.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.25.1)
>Requirement already satisfied: yt-dlp>=2022.04.08 in /home/media/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (2022.5.18)
>Requirement already satisfied: tmdbsimple>=2.7.0 in /home/media/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (2.9.1)
>Requirement already satisfied: unidecode>=1.1.1 in /home/media/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (1.3.4)
>Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from yt-dlp>=2022.04.08->-r requirements.txt (line 2)) (2020.6.20)
>Requirement already satisfied: pycryptodomex in /usr/lib/python3/dist-packages (from yt-dlp>=2022.04.08->-r requirements.txt (line 2)) (3.11.0)
>Requirement already satisfied: mutagen in /home/media/.local/lib/python3.10/site-packages (from yt-dlp>=2022.04.08->-r requirements.txt (line 2)) (1.45.1)
>Requirement already satisfied: brotli in /home/media/.local/lib/python3.10/site-packages (from yt-dlp>=2022.04.08->-r requirements.txt (line 2)) (1.0.9)
>Requirement already satisfied: websockets in /home/media/.local/lib/python3.10/site-packages (from yt-dlp>=2022.04.08->-r requirements.txt (line 2)) (10.3)


I'm getting new errors today while trying to install comictagger, another Python app, so it's clearly a problem on my end. If you want to close this issue as it's not a problem with TrailerTech, I'd be ok with that.

I may just nuke the OS from orbit. It's the only way to be sure :D

**Comment by jsaddiction** [comment]
This is certainly an interesting problem.  It does seem that there is something up with how your system references calls to "python3"

I did the same `ls` command on my recently update ubuntu VM to see if mine had links and apparently there was a change somewhere.  I got the same output.  I also did `python3 --version` and `python3.10 --version` where both commands returned 3.10.6.  I think after python3.8 they started packaging PIP with python.  I wonder if your pip3 installer is broken. 

Out of curiosity I ran the following commands.
`pip --verison` `pip3 --version`
Both returned `pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

I am willing to help if you are willing to keep trying.

**Comment by Tippon** [comment]
I'm definitely willing, I need to get this fixed one way or another >.<

I read something about how Ubuntu package Python differently, something about using the user space instead of the system space I think. I didn't really understand it, and there was nothing I could use to fix my issues, so I didn't save the page.

> Out of curiosity I ran the following commands.
> pip --verison pip3 --version
> Both returned `pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

I got this:

media@Media:~/Arr/TrailerTech$ pip --version
pip 22.2.2 from /home/media/.local/lib/python3.10/site-packages/pip (python 3.10)
media@Media:~/Arr/TrailerTech$ pip3 --version
pip 22.2.2 from /home/media/.local/lib/python3.10/site-packages/pip (python 3.10)

**Comment by jsaddiction** [comment]
So seems like the installation is right. Maybe there is something about how the packages are installed based on the user space.

Pip is global as represented in the paths listed in your last comment. If the packages are user based then the paths to those directories will exist in the user's home directory somewhere maybe in a hidden folder.

Try running the dependencies install with sudo which will tie the package to the root account. That should allow you to run via cronjob.

To follow up with that, you may need to install as if you were the radarr user. But there must be a way to install in the global space

**Comment by Tippon** [comment]
Installing as sudo tells me that the requirements are already satisfied, and I've got a feeling that I tried it before. This is the output though:

>sudo python3 -m pip install -r requirements.txt
>[sudo] password for media: 
>Requirement already satisfied: requests>=2.20.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.25.1)
>Requirement already satisfied: yt-dlp>=2022.04.08 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 2)) (2022.7.18)
>Requirement already satisfied: tmdbsimple>=2.7.0 in /root/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (2.9.1)
>Requirement already satisfied: unidecode>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 4)) (1.3.4)
>Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from yt-dlp>=2022.04.08->-r requirements.txt (line 2)) (2020.6.20)
>Requirement already satisfied: pycryptodomex in /usr/lib/python3/dist-packages (from yt-dlp>=2022.04.08->-r requirements.txt (line 2)) (3.11.0)
>Requirement already satisfied: mutagen in /usr/local/lib/python3.10/dist-packages (from yt-dlp>=2022.04.08->-r requirements.txt (line 2)) (1.45.1)
>Requirement already satisfied: websockets in /usr/local/lib/python3.10/dist-packages (from yt-dlp>=2022.04.08->-r requirements.txt (line 2)) (10.3)
>Requirement already satisfied: brotli in /usr/local/lib/python3.10/dist-packages (from yt-dlp>=2022.04.08->-r requirements.txt (line 2)) (1.0.9)
>WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

TrailerTech will run from the terminal, and seems to be running through a cron job, but is getting the code 1 error when trying to run from Radarr.

**Comment by jsaddiction** [comment]
When radarr was installed there was probably a user/group that was added which radarr runs with.

`cat /etc/passwd`
`cat /etc/group`

Those commands will list out users and groups respectively. Don't post the results. Not secret but not everyone needs to know.

If the radarr user does not have access to the python you have installed or the dependencies in the requirements file then you have found your problem.

Do some googlin and switch your current logged in user to the radarr user and try running the script / installing the dependencies. This should give you more verbose output from the shell

**Comment by Tippon** [comment]
Holy crap, it's worked! :D

I found an issue on Reddit where someone could only run Radarr as root, and one of the answers was to try running it as another user. Here for reference:

[https://www.reddit.com/r/radarr/comments/9ptgwi/comment/e84fi9o/?utm_source=share&utm_medium=web2x&context=3](https://www.reddit.com/r/radarr/comments/9ptgwi/comment/e84fi9o/?utm_source=share&utm_medium=web2x&context=3)

After a few false starts, like forgetting that the radarr user isn't a sudoer, and that I had to change back to the TrailerTech folder, I switched to the radarr user, installed the requirements.txt, which installed tmdbsimple under the radarr user's home, then set TrailerTech up in Radarr in the way your guide shows, and this time it worked! :D

The terminal output is here:

[https://pastebin.com/5ESbcPr7](https://pastebin.com/5ESbcPr7)

The Radarr logs are here:

[https://pastebin.com/uNxJU6mL](https://pastebin.com/uNxJU6mL)


Thank you so much for helping me get to the bottom of this, it would have bugged me for months, probably longer

**Comment by jsaddiction** [comment]
I am glad we got it resolved! Enjoy your trailers!
