### ISSUE TITLE
TrailerTech not running

### ISSUE THREAD

**Issue by bozrdang** [jsaddiction/TrailerTech#48]
I've been running TrailerTech with Radar in a Docker container for a couple years now without issue.  The other day I updated the Radarr container and now the container log keeps repeating this same message:

```
********** INSTALLING git **********
********** INSTALLING python3 **********
********** INSTALLING python3-pip **********
ERROR: unable to select packages:
  python3-pip (no such package):
    required by: world[python3-pip]
********** INSTALLING ffmpeg **********
********** UPDATING TrailerTech **********
Failed to update local repo. ERROR: fatal: detected dubious ownership in repository at '/config/scripts/TrailerTech'
To add an exception for this directory, call:

        git config --global --add safe.directory /config/scripts/TrailerTech
********** Setting Permissions for TrailerTechnician **********
********** Installing TrailerTech Dependencies **********
Failed to install dependencies. ERROR: /usr/bin/python3: No module named pip
```

Any idea on how to sort this?

**Comment by jsaddiction** [comment]
The install script has been update recently please ensure you are using the most recent version of that script.  You will have to do some "copy paste" or other method to get it into your custom-init directory.

**Comment by bozrdang** [comment]
I replaced the script and I now get this message:

```
[Warn] RadarrErrorPipeline: Invalid request Validation failed: 
 -- : An error occurred trying to start process '/config/scripts/TrailerTech/TrailerTech.py' with working directory '/app/radarr/bin'. Permission denied 
```

**Comment by jsaddiction** [comment]
looks like a permissions error with the script.  When you establish your Radarr container I assume you set the environment variables "PUID and PGID" to some value.  Whatever those are set to should also be the "owner" of the directory "TrailerTech" and everything below it in the tree.

One solution could be to copy your settings.ini somewhere locally (as a backup) then build your container and then copy over your settings.ini file back.

Another solution would be to inspect the linux permissions by running `docker exec -it <container name> /bin/bash` then navigate to the scripts directory and run the `ls -al` command to see who the owner is and ensure it has executable permissions by the containers user.  Once you figure that out, you could then `chown -R` and `chmod -R` that directory for the same user that runs RADARR.

**Comment by bozrdang** [comment]
I'll look into that. Thanks!

**Comment by bozrdang** [comment]
I finally got it working.  First, I copied and pasted the Install_TrailerTech.sh and that didn't work,  But then I manually created the fil from withing the container and pasted the file contents and all is good.  Thanks!

And thanks for such a handy script.

**Comment by jsaddiction** [comment]
Creating that file from within the container would have established the appropriate "owner" for the script to run.  Glad you got it sorted out!

Thank you for your support!
