### ISSUE TITLE
Update wiki to match LinuxServer's Docker custom script changes

### ISSUE THREAD

**Issue by Mavyre** [jsaddiction/TrailerTech#56]
As per [this article](https://info.linuxserver.io/issues/2022-08-29-custom-files/), the sc cript folder is located in /custom-cont-init.d instead of under /config/custom-cont-init.d. This would be great to update the [Install wiki page](https://github.com/jsaddiction/TrailerTech/wiki/Install-Script) to reflect these changes.

**Comment by jsaddiction** [comment]
Good catch!  I had fixed this locally, but failed to update the wiki.  Thanks for keeping me honest.
